/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminInviteRouteImport } from './routes/admin.invite'
import { Route as ApiAdminConfigRouteImport } from './routes/api/admin/config'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInviteRoute = AdminInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminConfigRoute = ApiAdminConfigRouteImport.update({
  id: '/api/admin/config',
  path: '/api/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/invite': typeof AdminInviteRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/invite': typeof AdminInviteRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/invite': typeof AdminInviteRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/admin/invite' | '/api/admin/config'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/admin/invite' | '/api/admin/config'
  id: '__root__' | '/' | '/admin' | '/admin/invite' | '/api/admin/config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiAdminConfigRoute: typeof ApiAdminConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invite': {
      id: '/admin/invite'
      path: '/invite'
      fullPath: '/admin/invite'
      preLoaderRoute: typeof AdminInviteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/config': {
      id: '/api/admin/config'
      path: '/api/admin/config'
      fullPath: '/api/admin/config'
      preLoaderRoute: typeof ApiAdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminInviteRoute: typeof AdminInviteRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInviteRoute: AdminInviteRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiAdminConfigRoute: ApiAdminConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
